VOCAB_SIZE = int(1e5 * 2.5)

SENTENCE_LEN = 64
BATCH_SIZE = 512
WORKERS = 8
N_EPOCHS = 50
LEARNING_RATE = 1e-5

DATASET_FNAME = "./dataset/dataset.csv"
VALIDATION_FNAME = "./dataset/validation.csv"

VALIDATION_DS_ROWS = 512

PAD_TOKEN = "<PAD>"
START_TOKEN = "<START>"
END_TOKEN = "<END>"
UNKNOWN_TOKEN = "<UKN>"
