VOCAB_SIZE = int(1e5 * 2.5)

SENTENCE_LEN = 64
BATCH_SIZE = 1024
WORKERS = 8
N_EPOCHS = 15
LEARNING_RATE = 1e-3

DATASET_FNAME = "./dataset/dataset.csv"
PAD_TOKEN = "<PAD>"
START_TOKEN = "<START>"
END_TOKEN = "<END>"
UNKNOWN_TOKEN = "<UKN>"
